# Generated by Django 3.0.8 on 2020-07-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200717_1226'),
        ('accounts', '0002_userpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='purchases_m2m', to='games.Game'),
        ),
    ]
