# Generated by Django 3.0.8 on 2020-07-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200718_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPurchase',
        ),
    ]
