# Generated by Django 3.0.8 on 2020-07-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Collection'),
        ),
    ]
