# Generated by Django 3.0.8 on 2020-07-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200717_1226'),
        ('features', '0005_auto_20200719_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to='games.Game'),
        ),
    ]
