# Generated by Django 3.0.8 on 2020-07-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20200719_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiplayerinvite',
            unique_together=set(),
        ),
    ]
