# Generated by Django 3.0.8 on 2020-07-19 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200717_1226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0007_auto_20200719_2230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiplayerinvite',
            unique_together={('invitesender', 'invitereceiver', 'game')},
        ),
    ]
