# Generated by Django 3.0.8 on 2020-07-16 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(primary_key=True, serialize=False)),
                ('groupid', models.CharField(default=uuid.uuid4, max_length=40)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('timemodified', models.DateTimeField(auto_now=True)),
                ('datereleased', models.DateField(default=datetime.date.today)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='games.Collection')),
            ],
        ),
    ]
