# Generated by Django 3.0.8 on 2020-07-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200717_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='games.Collection'),
        ),
    ]
